name: awesome_stepper
description: A new Flutter package project.
version: 0.0.1
homepage: null
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  kartal: ^2.2.0
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
flutter: null
