name: awesome_stepper
description: A Customizable Awesome Stepper with beautiful UI to develop awesome steppers.
version: 0.1.3
homepage: https://github.com/msaadev/
repository: https://github.com/msaadev/awesome_stepper
documentation: https://github.com/msaadev/awesome_stepper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
flutter: null
